// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK0s42pSDPmwmTtPaf1S3us9oHDB3EHRQ',
    appId: '1:304822853034:web:2d76e623f2b5cba13edfd3',
    messagingSenderId: '304822853034',
    projectId: 'voki-35693',
    authDomain: 'voki-35693.firebaseapp.com',
    storageBucket: 'voki-35693.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1c8pF0Ytq_A_zNw78Hx2EAMH1AE_2ChA',
    appId: '1:304822853034:android:9ace3f5bd6af85713edfd3',
    messagingSenderId: '304822853034',
    projectId: 'voki-35693',
    storageBucket: 'voki-35693.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJJi8Q5JfwhkPqDns5LkOFvD8Ho2QSywA',
    appId: '1:304822853034:ios:3df7ae2ad68742163edfd3',
    messagingSenderId: '304822853034',
    projectId: 'voki-35693',
    storageBucket: 'voki-35693.firebasestorage.app',
    iosBundleId: 'com.example.vokiNuevo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJJi8Q5JfwhkPqDns5LkOFvD8Ho2QSywA',
    appId: '1:304822853034:ios:3df7ae2ad68742163edfd3',
    messagingSenderId: '304822853034',
    projectId: 'voki-35693',
    storageBucket: 'voki-35693.firebasestorage.app',
    iosBundleId: 'com.example.vokiNuevo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK0s42pSDPmwmTtPaf1S3us9oHDB3EHRQ',
    appId: '1:304822853034:web:317aca6d79bce73a3edfd3',
    messagingSenderId: '304822853034',
    projectId: 'voki-35693',
    authDomain: 'voki-35693.firebaseapp.com',
    storageBucket: 'voki-35693.firebasestorage.app',
  );
}
